#!/bin/bash

basepath=$(cd `dirname $0`; pwd)
trashpath=$($basepath/getTrashPath)
realrm="/bin/rm"


if [ ! -d  "$trashpath" ]
then
	mkdir -v $trashpath
	chmod 777 $trashpath
fi

if [ $# -eq 0 ]
then
	echo "Usage: delete file1 [file2 file3 ...]"
	echo "If the option contain -f, then the script will exec 'rm' directly"
fi

while getopts "dfiPRrvW" opt
do
	case $opt in
		f)
			exec $realrm "$@"
			;;
		*)
			# do nothing
			;;
	esac
done

echo -ne "Are you sure you want to move the files to the trash? [Y/N]: \a"
read reply
if [ $reply = "y" -o $reply = "Y" ]
then
	for file in $@
	do
		if [ -f "$file" -o -d "$file" ]
		then
			if [ -f "$file" ] && [ `ls -l $file | awk '{print $5}'` -gt 2147483648 ]
			then
				echo "$file size is larger than 2G, will be deleted directly"
				`rm -rf $file`
			elif [ -d "$file" ] && [ `du -sb $file | awk '{print $1}'` -gt 2147483648 ]
			then
				echo "The directory:$file is larger than 2G, will be deleted directly"
				`rm -rf $file`
			fi
		fi
	done
fi

now=`date +%Y%m%d_%H_%M_%S`
filename="${file##*/}"
newfilename="${file##*/}_${now}"
filedst=$trashpath/$newfilename
mark1="."
mark2="/"

if [ "$file" = ${file/$mark2} ]
then
	fullpath="$(pwd)/$file"
elif [ "$file" != ${file/$mark1} ]
then
	fullpath="$(pwd)${file/$mark1}"
else
	fullpath="$file"
fi
echo "The full path of this file is : $fullpath"
if mv -f "$file" "$filedst"
then
	$($basepath/logTrashDir "$newfilename $filename $now $fullpath")
	echo "Operation succeed!"
else
	echo "Operation failed"
fi
